server:
  port: 8083

spring:
  application:
    name: CATEGORY-SERVICE
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
